name: Update Cyclist Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas plotly

    - name: Run cyclist analyzer script
      run: |
        echo "Python version:"
        python --version
        echo "Installed packages:"
        pip list
        echo "Running script..."
        python cyclist_analyzer.py > cyclist-data.json 2>error.log
        echo "Script execution completed"
        echo "Error log contents:"
        cat error.log
        echo "First 1000 characters of cyclist-data.json:"
        head -c 1000 cyclist-data.json
        echo "File size of cyclist-data.json:"
        ls -l cyclist-data.json
        if [ ! -s cyclist-data.json ]; then
          echo "Error: cyclist-data.json is empty or does not exist"
          exit 1
        fi

    - name: Check for changes
      id: git-check
      run: |
        git status
        git diff --exit-code cyclist-data.json || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Commit and push if changed
      if: steps.git-check.outputs.changes == 'true'
      run: |
        echo "Changes detected, committing and pushing..."
        git config --global user.name 'mhke0'
        git config --global user.email 'moritzhacke@gmail.com'
        git add cyclist-data.json
        git commit -m "Update cyclist data [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: No changes detected
      if: steps.git-check.outputs.changes != 'true'
      run: echo "No changes in cyclist-data.json, skipping commit"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cyclist-data
        path: |
          cyclist-data.json
          error.log
