name: Update Cyclist Data and League Scores

on:
  schedule:
    - cron: '0 20 * * *'  # Runs daily at 20:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Create requirements.txt
      run: |
        echo "requests" > requirements.txt
        echo "beautifulsoup4" >> requirements.txt
        echo "pandas" >> requirements.txt
        echo "plotly" >> requirements.txt
        echo "pulp" >> requirements.txt
        echo "numpy" >> requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run cyclist analyzer script
      run: python cyclist_analyzer.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'mhke0'
        git config --global user.email 'moritzhacke@gmail.com'
        git add cyclist-data.json requirements.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update cyclist data and league scores [skip ci]" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
