name: Update Cyclist Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas plotly
    - name: Run cyclist analyzer script
      run: |
        echo "Python version:"
        python --version
        echo "Installed packages:"
        pip list
        echo "Running script..."
        python cyclist_analyzer.py > cyclist-data.json 2>error.log
        echo "Error log contents:"
        cat error.log
        echo "First 1000 characters of cyclist-data.json:"
        head -c 1000 cyclist-data.json
        if [ ! -s cyclist-data.json ]; then
          echo "Error: cyclist-data.json is empty"
          exit 1
        fi
    - name: Commit and push if changed
      if: success()
      run: |
        git config --global user.email "moritzhacke@gmail.com"
        git config --global user.name "mhke0"
        git add cyclist-data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update cyclist data [skip ci]" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
