name: Update Cyclist Data and League Scores
on:
  schedule:
    - cron: '0 17 17-31 8 *'  # Runs daily at 17:00 UTC from August 17 to 31
    - cron: '0 17 1-8 9 *'    # Runs daily at 17:00 UTC from September 1 to 8
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Check date
      id: check_date
      run: |
        current_date=$(date +'%Y-%m-%d')
        if [[ "$current_date" == "2024-08-26" || "$current_date" == "2024-09-02" ]]; then
          echo "skip=true" >> $GITHUB_OUTPUT
        else
          echo "skip=false" >> $GITHUB_OUTPUT
        fi

    - name: Set up Python
      if: steps.check_date.outputs.skip == 'false'
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Create requirements.txt
      if: steps.check_date.outputs.skip == 'false'
      run: |
        echo "requests" > requirements.txt
        echo "beautifulsoup4" >> requirements.txt
        echo "pandas" >> requirements.txt
        echo "plotly" >> requirements.txt
        echo "pulp" >> requirements.txt
        echo "numpy" >> requirements.txt

    - name: Install dependencies
      if: steps.check_date.outputs.skip == 'false'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run cyclist analyzer script
      if: steps.check_date.outputs.skip == 'false'
      run: python cyclist_analyzer.py

    - name: Commit and push if changed
      if: steps.check_date.outputs.skip == 'false'
      run: |
        git config --global user.name 'mhke0'
        git config --global user.email 'moritzhacke@gmail.com'
        git add cyclist-data.json requirements.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update cyclist data and league scores [skip ci]" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
